name = "bed-jeffnawroth-me"
main = "src/index.ts"
compatibility_date = "2026-09-05"

[assets]
directory = "../web/out"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = [ "/api/*" ]

[observability]
enabled = true
