services:
  frontend:
    build:
      context: ./frontend
    networks:
      - webnet
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION_STRING=mongodb://mongo:27017/emissions
    depends_on:
      - mongo
    networks:
      - webnet
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - webnet
    restart: always


  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - webnet
    restart: always

networks:
  webnet:

volumes:
  caddy_data:
  caddy_config:
