/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    BarChartCard: typeof import('./components/Dashboard/BarChartCard.vue')['default']
    CountriesCard: typeof import('./components/Dashboard/CountriesCard.vue')['default']
    DataCard: typeof import('./components/Dashboard/DataCard.vue')['default']
    EmissionTypeCard: typeof import('./components/Dashboard/EmissionTypeCard.vue')['default']
    GasSelectCard: typeof import('./components/Dashboard/GasSelectCard.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderCard: typeof import('./components/Dashboard/SliderCard.vue')['default']
  }
}
