/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    BarChartCard: typeof import('./components/Dashboard/BarChartCard/BarChartCard.vue')['default']
    Co2SubtitleTooltip: typeof import('./components/Dashboard/BarChartCard/Subtitle/Co2SubtitleTooltip.vue')['default']
    CountriesCard: typeof import('./components/Dashboard/CountriesCard.vue')['default']
    DataCard: typeof import('./components/Dashboard/DataCard.vue')['default']
    DistributionDataTable: typeof import('./components/Dashboard/BarChartCard/DistributionDataTable.vue')['default']
    EmissionTypeCard: typeof import('./components/Dashboard/EmissionTypeCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GhgSubtitleTooltip: typeof import('./components/Dashboard/BarChartCard/Subtitle/GhgSubtitleTooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderCard: typeof import('./components/Dashboard/SliderCard.vue')['default']
    Subtitle: typeof import('./components/Dashboard/BarChartCard/Subtitle/Subtitle.vue')['default']
    SubtitleTooltip: typeof import('./components/Dashboard/BarChartCard/Subtitle/SubtitleTooltip.vue')['default']
  }
}
