interface Company {
  rank: number
  company: string
  region: string
  country: string
  sector: string
  industry: string
  esg_score: number
  temperature_score: number | string
  emissions_scope_1_2: number
  emissions_scope_3: number | null
  market_cap_category: string
}

export default [

  {
    rank: 1,
    company: 'ASML Holdings N.V.',
    region: 'Europe',
    country: 'Netherlands',
    sector: 'Electronic Technology',
    industry: 'Semiconductors',
    esg_score: 73.13,
    temperature_score: 1.5,
    emissions_scope_1_2: 155200,
    emissions_scope_3: 8400000,
    market_cap_category: 'Mega',
  },
  {
    rank: 2,
    company: 'Check Point Software Technologies',
    region: 'Middle East',
    country: 'Israel',
    sector: 'Technology Services',
    industry: 'Internet Software/Services',
    esg_score: 72.64,
    temperature_score: 3,
    emissions_scope_1_2: 15323,
    emissions_scope_3: 21531,
    market_cap_category: 'Large',
  },
  {
    rank: 3,
    company: 'Hermes International SCA',
    region: 'Europe',
    country: 'France',
    sector: 'Consumer Non-Durables',
    industry: 'Apparel/Footwear',
    esg_score: 71.71,
    temperature_score: 1.5,
    emissions_scope_1_2: 34600,
    emissions_scope_3: 486400,
    market_cap_category: 'Large',
  },
  {
    rank: 4,
    company: 'Linde',
    region: 'Europe',
    country: 'United Kingdom',
    sector: 'Process Industries',
    industry: 'Chemicals: Specialty',
    esg_score: 71.26,
    temperature_score: '>2.7',
    emissions_scope_1_2: 37734000,
    emissions_scope_3: 21261000,
    market_cap_category: 'Large',
  },
  {
    rank: 5,
    company: 'Kone Oyj',
    region: 'Europe',
    country: 'Finland',
    sector: 'Producer Manufacturing',
    industry: 'Building Products',
    esg_score: 70.37,
    temperature_score: 1.5,
    emissions_scope_1_2: 135100,
    emissions_scope_3: 14105500,
    market_cap_category: 'Large',
  },
  {
    rank: 6,
    company: 'Shionogi & Co.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Health Technology',
    industry: 'Pharmaceuticals: Major',
    esg_score: 70.04,
    temperature_score: 1.5,
    emissions_scope_1_2: 81730,
    emissions_scope_3: 118790,
    market_cap_category: 'Large',
  },
  {
    rank: 7,
    company: 'Applied Materials, Inc.',
    region: 'North America',
    country: 'United States',
    sector: 'Producer Manufacturing',
    industry: 'Industrial Machinery',
    esg_score: 69.77,
    temperature_score: 3,
    emissions_scope_1_2: 303311,
    emissions_scope_3: 8400,
    market_cap_category: 'Large',
  },
  {
    rank: 8,
    company: 'Beiersdorf AG',
    region: 'Europe',
    country: 'Germany',
    sector: 'Consumer Non-Durables',
    industry: 'Household/Personal Care',
    esg_score: 69.7,
    temperature_score: 1.5,
    emissions_scope_1_2: 102027,
    emissions_scope_3: 1041703,
    market_cap_category: 'Large',
  },
  {
    rank: 9,
    company: 'Colgate-Palmolive company',
    region: 'North America',
    country: 'United States',
    sector: 'Consumer Non-Durables',
    industry: 'Household/Personal Care',
    esg_score: 69.32,
    temperature_score: 1.5,
    emissions_scope_1_2: 577679,
    emissions_scope_3: 41966000,
    market_cap_category: 'Large',
  },
  {
    rank: 10,
    company: 'L\'Oreal S.A.',
    region: 'Europe',
    country: 'France',
    sector: 'Consumer Non-Durables',
    industry: 'Household/Personal Care',
    esg_score: 69.3,
    temperature_score: 1.5,
    emissions_scope_1_2: 55778,
    emissions_scope_3: 11169000,
    market_cap_category: 'Mega',
  },
  {
    rank: 11,
    company: 'CLP Holdings Limited',
    region: 'Asia',
    country: 'Hong Kong',
    sector: 'Utilities',
    industry: 'Electric Utilities',
    esg_score: 68.74,
    temperature_score: 2,
    emissions_scope_1_2: 47926000,
    emissions_scope_3: 17091000,
    market_cap_category: 'Large',
  },
  {
    rank: 12,
    company: 'Unicharm Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Household/Personal Care',
    esg_score: 68.69,
    temperature_score: 3,
    emissions_scope_1_2: 466000,
    emissions_scope_3: 1942000,
    market_cap_category: 'Large',
  },
  {
    rank: 13,
    company: 'Atlas Copco',
    region: 'Europe',
    country: 'Sweden',
    sector: 'Producer Manufacturing',
    industry: 'Industrial Machinery',
    esg_score: 68.67,
    temperature_score: 1.5,
    emissions_scope_1_2: 115000,
    emissions_scope_3: 124000,
    market_cap_category: 'Large',
  },
  {
    rank: 14,
    company: 'Fortinet, Inc.',
    region: 'North America',
    country: 'United States',
    sector: 'Electronic Technology',
    industry: 'Computer Communications',
    esg_score: 68.49,
    temperature_score: 1.5,
    emissions_scope_1_2: 4766,
    emissions_scope_3: 318336,
    market_cap_category: 'Large',
  },
  {
    rank: 15,
    company: 'Xylem Inc.',
    region: 'North America',
    country: 'United States',
    sector: 'Producer Manufacturing',
    industry: 'Industrial Machinery',
    esg_score: 68.48,
    temperature_score: 1.5,
    emissions_scope_1_2: 88990,
    emissions_scope_3: 1968049,
    market_cap_category: 'Large',
  },
  {
    rank: 16,
    company: 'ABB Ltd.',
    region: 'Europe',
    country: 'Switzerland',
    sector: 'Producer Manufacturing',
    industry: 'Electrical Products',
    esg_score: 68.46,
    temperature_score: 1.5,
    emissions_scope_1_2: 537000,
    emissions_scope_3: 6126000,
    market_cap_category: 'Large',
  },
  {
    rank: 17,
    company: 'Hong Kong Exchanges & Clearing Ltd.',
    region: 'Asia',
    country: 'Hong Kong',
    sector: 'Finance',
    industry: 'Investment Banks/Brokers',
    esg_score: 68.27,
    temperature_score: 2,
    emissions_scope_1_2: 19288,
    emissions_scope_3: 978,
    market_cap_category: 'Large',
  },
  {
    rank: 18,
    company: 'Canadian Natural Resources Limited',
    region: 'North America',
    country: 'Canada',
    sector: 'Energy Minerals',
    industry: 'Oil & Gas Production',
    esg_score: 68.16,
    temperature_score: 3,
    emissions_scope_1_2: 9030736,
    emissions_scope_3: 131871838,
    market_cap_category: 'Large',
  },
  {
    rank: 19,
    company: 'Geberit AG',
    region: 'Europe',
    country: 'Switzerland',
    sector: 'Producer Manufacturing',
    industry: 'Building Products',
    esg_score: 68.07,
    temperature_score: 2,
    emissions_scope_1_2: 206553,
    emissions_scope_3: 767119,
    market_cap_category: 'Large',
  },
  {
    rank: 20,
    company: 'Edwards Lifesciences Corporation',
    region: 'North America',
    country: 'United States',
    sector: 'Health Technology',
    industry: 'Medical Specialties',
    esg_score: 68.02,
    temperature_score: 1.5,
    emissions_scope_1_2: 47759,
    emissions_scope_3: 31264,
    market_cap_category: 'Large',
  },
  {
    rank: 21,
    company: 'Weyerhaeuser company',
    region: 'North America',
    country: 'United States',
    sector: 'Finance',
    industry: 'Real Estate Investment Trusts',
    esg_score: 67.9,
    temperature_score: 2,
    emissions_scope_1_2: 1019681,
    emissions_scope_3: 6100000,
    market_cap_category: 'Large',
  },
  {
    rank: 22,
    company: 'Mondi plc',
    region: 'Europe',
    country: 'United Kingdom',
    sector: 'Process Industries',
    industry: 'Containers/Packaging',
    esg_score: 67.83,
    temperature_score: '>2.7',
    emissions_scope_1_2: 3910215,
    emissions_scope_3: 3253460,
    market_cap_category: 'Large',
  },
  {
    rank: 23,
    company: 'Geely Automobile Holdings Limited',
    region: 'Asia',
    country: 'Hong Kong',
    sector: 'Consumer Durables',
    industry: 'Motor Vehicles',
    esg_score: 67.77,
    temperature_score: 1.5,
    emissions_scope_1_2: 663984,
    emissions_scope_3: 11534383,
    market_cap_category: 'Large',
  },
  {
    rank: 24,
    company: 'Cognex Corporation',
    region: 'North America',
    country: 'United States',
    sector: 'Electronic Technology',
    industry: 'Electronic Equipment/Instruments',
    esg_score: 67.63,
    temperature_score: 3,
    emissions_scope_1_2: 16451,
    emissions_scope_3: 273834,
    market_cap_category: 'Large',
  },
  {
    rank: 25,
    company: 'Kao Corp.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Household/Personal Care',
    esg_score: 67.61,
    temperature_score: 2,
    emissions_scope_1_2: 899000,
    emissions_scope_3: 11184000,
    market_cap_category: 'Large',
  },
  {
    rank: 26,
    company: 'Logitech International S.A.',
    region: 'Europe',
    country: 'Switzerland',
    sector: 'Electronic Technology',
    industry: 'Computer Peripherals',
    esg_score: 67.58,
    temperature_score: 1.5,
    emissions_scope_1_2: 1461,
    emissions_scope_3: 1299592,
    market_cap_category: 'Large',
  },
  {
    rank: 27,
    company: 'VERBUND AG',
    region: 'Europe',
    country: 'Austria',
    sector: 'Utilities',
    industry: 'Electric Utilities',
    esg_score: 67.48,
    temperature_score: 2,
    emissions_scope_1_2: 1059000,
    emissions_scope_3: 335000,
    market_cap_category: 'Large',
  },
  {
    rank: 28,
    company: 'BYD company',
    region: 'Asia',
    country: 'China',
    sector: 'Consumer Durables',
    industry: 'Motor Vehicles',
    esg_score: 67.34,
    temperature_score: 3,
    emissions_scope_1_2: 388442,
    emissions_scope_3: 16536868,
    market_cap_category: 'Mega',
  },
  {
    rank: 29,
    company: 'Goodman Group',
    region: 'Pacific Rim',
    country: 'Australia',
    sector: 'Finance',
    industry: 'Real Estate Investment Trusts',
    esg_score: 67.34,
    temperature_score: 2,
    emissions_scope_1_2: 40560,
    emissions_scope_3: 12308,
    market_cap_category: 'Large',
  },
  {
    rank: 30,
    company: 'Li Ning company Limited',
    region: 'Asia',
    country: 'China',
    sector: 'Consumer Non-Durables',
    industry: 'Apparel/Footwear',
    esg_score: 67.34,
    temperature_score: 1.5,
    emissions_scope_1_2: 4735,
    emissions_scope_3: null,
    market_cap_category: 'Large',
  },
  {
    rank: 31,
    company: 'Texas Instruments Incorporated',
    region: 'North America',
    country: 'United States',
    sector: 'Electronic Technology',
    industry: 'Semiconductors',
    esg_score: 67.27,
    temperature_score: 2.7,
    emissions_scope_1_2: 2133617,
    emissions_scope_3: 4630,
    market_cap_category: 'Large',
  },
  {
    rank: 32,
    company: 'Marathon Oil Corporation',
    region: 'North America',
    country: 'United States',
    sector: 'Energy Minerals',
    industry: 'Oil & Gas Production',
    esg_score: 67.26,
    temperature_score: '>2.7',
    emissions_scope_1_2: 3705000,
    emissions_scope_3: 42580000,
    market_cap_category: 'Large',
  },
  {
    rank: 33,
    company: 'OMRON Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Electronic Technology',
    industry: 'Electronic Equipment/Instruments',
    esg_score: 67.19,
    temperature_score: 1.5,
    emissions_scope_1_2: 123394,
    emissions_scope_3: 10996115,
    market_cap_category: 'Large',
  },
  {
    rank: 34,
    company: 'Tokyo Electron Ltd.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Producer Manufacturing',
    industry: 'Industrial Machinery',
    esg_score: 67.16,
    temperature_score: 1.5,
    emissions_scope_1_2: 186000,
    emissions_scope_3: 6222000,
    market_cap_category: 'Large',
  },
  {
    rank: 35,
    company: 'Keysight Technologies Inc',
    region: 'North America',
    country: 'United States',
    sector: 'Electronic Technology',
    industry: 'Electronic Equipment/Instruments',
    esg_score: 67.05,
    temperature_score: 1.5,
    emissions_scope_1_2: 88314,
    emissions_scope_3: 99445,
    market_cap_category: 'Large',
  },
  {
    rank: 36,
    company: 'Teck Resources Limited',
    region: 'North America',
    country: 'Canada',
    sector: 'Basic Industries',
    industry: 'Metal Mining',
    esg_score: 67.03,
    temperature_score: 3,
    emissions_scope_1_2: 13400000,
    emissions_scope_3: 35000000,
    market_cap_category: 'Large',
  },
  {
    rank: 37,
    company: 'Epiroc AB',
    region: 'Europe',
    country: 'Sweden',
    sector: 'Producer Manufacturing',
    industry: 'Industrial Machinery',
    esg_score: 66.98,
    temperature_score: 1.5,
    emissions_scope_1_2: 86932,
    emissions_scope_3: 107000,
    market_cap_category: 'Large',
  },
  {
    rank: 38,
    company: 'SAP SE',
    region: 'Europe',
    country: 'Germany',
    sector: 'Technology Services',
    industry: 'Computer Software: Prepackaged Software',
    esg_score: 66.97,
    temperature_score: 1.5,
    emissions_scope_1_2: 294000,
    emissions_scope_3: 3060000,
    market_cap_category: 'Mega',
  },
  {
    rank: 39,
    company: 'Toyota Motor Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Durables',
    industry: 'Motor Vehicles',
    esg_score: 66.97,
    temperature_score: 1.5,
    emissions_scope_1_2: 2897000,
    emissions_scope_3: 49900000,
    market_cap_category: 'Mega',
  },
  {
    rank: 40,
    company: 'CNOOC Limited',
    region: 'Asia',
    country: 'Hong Kong',
    sector: 'Energy Minerals',
    industry: 'Oil & Gas Production',
    esg_score: 66.95,
    temperature_score: '>2.7',
    emissions_scope_1_2: 30100000,
    emissions_scope_3: 69040000,
    market_cap_category: 'Large',
  },
  {
    rank: 41,
    company: 'Coca-Cola HBC AG',
    region: 'Europe',
    country: 'Switzerland',
    sector: 'Consumer Non-Durables',
    industry: 'Beverages (Production/Distribution)',
    esg_score: 66.86,
    temperature_score: 1.5,
    emissions_scope_1_2: 36761,
    emissions_scope_3: 654979,
    market_cap_category: 'Large',
  },
  {
    rank: 42,
    company: 'Nestle S.A.',
    region: 'Europe',
    country: 'Switzerland',
    sector: 'Consumer Non-Durables',
    industry: 'Packaged Foods',
    esg_score: 66.84,
    temperature_score: 1.5,
    emissions_scope_1_2: 982107,
    emissions_scope_3: 4094549,
    market_cap_category: 'Mega',
  },
  {
    rank: 43,
    company: 'Medtronic plc',
    region: 'Europe',
    country: 'Ireland',
    sector: 'Health Technology',
    industry: 'Medical Specialties',
    esg_score: 66.83,
    temperature_score: 1.5,
    emissions_scope_1_2: 65204,
    emissions_scope_3: 1205746,
    market_cap_category: 'Mega',
  },
  {
    rank: 44,
    company: 'Medtronic plc',
    region: 'North America',
    country: 'United States',
    sector: 'Health Technology',
    industry: 'Medical Specialties',
    esg_score: 66.83,
    temperature_score: 1.5,
    emissions_scope_1_2: 65204,
    emissions_scope_3: 1205746,
    market_cap_category: 'Mega',
  },
  {
    rank: 45,
    company: 'Sodexo',
    region: 'Europe',
    country: 'France',
    sector: 'Consumer Services',
    industry: 'Restaurants',
    esg_score: 66.81,
    temperature_score: 1.5,
    emissions_scope_1_2: 350800,
    emissions_scope_3: 510700,
    market_cap_category: 'Large',
  },
  {
    rank: 46,
    company: 'Denso Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Producer Manufacturing',
    industry: 'Auto Parts: OEM',
    esg_score: 66.8,
    temperature_score: 1.5,
    emissions_scope_1_2: 192000,
    emissions_scope_3: 1870000,
    market_cap_category: 'Large',
  },
  {
    rank: 47,
    company: 'Bank of America Corp.',
    region: 'North America',
    country: 'United States',
    sector: 'Finance',
    industry: 'Major Banks',
    esg_score: 66.79,
    temperature_score: 2,
    emissions_scope_1_2: 3802745,
    emissions_scope_3: 67921839,
    market_cap_category: 'Mega',
  },
  {
    rank: 48,
    company: 'SK hynix Inc.',
    region: 'Asia',
    country: 'South Korea',
    sector: 'Electronic Technology',
    industry: 'Semiconductors',
    esg_score: 66.78,
    temperature_score: 1.5,
    emissions_scope_1_2: 6171235,
    emissions_scope_3: 1416000,
    market_cap_category: 'Large',
  },
  {
    rank: 49,
    company: 'Equinix, Inc. (REIT)',
    region: 'North America',
    country: 'United States',
    sector: 'Finance',
    industry: 'Real Estate Investment Trusts',
    esg_score: 66.76,

    temperature_score: 2,
    emissions_scope_1_2: 4886,
    emissions_scope_3: 432,
    market_cap_category: 'Mega',
  },
  {
    rank: 50,
    company: 'NTT DATA Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Technology Services',
    industry: 'EDP Services',
    esg_score: 66.74,
    temperature_score: 1.5,
    emissions_scope_1_2: 137287,
    emissions_scope_3: 2300262,
    market_cap_category: 'Large',
  },
  {
    rank: 51,
    company: 'H&M Hennes & Mauritz AB',
    region: 'Europe',
    country: 'Sweden',
    sector: 'Consumer Services',
    industry: 'Clothing/Shoe/Accessory Stores',
    esg_score: 66.72,
    temperature_score: 1.5,
    emissions_scope_1_2: 67992,
    emissions_scope_3: 888046,
    market_cap_category: 'Large',
  },
  {
    rank: 52,
    company: 'Zalando SE',
    region: 'Europe',
    country: 'Germany',
    sector: 'Consumer Services',
    industry: 'Clothing/Shoe/Accessory Stores',
    esg_score: 66.71,
    temperature_score: 1.5,
    emissions_scope_1_2: 18796,
    emissions_scope_3: 157190,
    market_cap_category: 'Large',
  },
  {
    rank: 53,
    company: 'Daikin Industries, Ltd.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Producer Manufacturing',
    industry: 'Industrial Machinery',
    esg_score: 66.7,
    temperature_score: 1.5,
    emissions_scope_1_2: 364000,
    emissions_scope_3: 2170000,
    market_cap_category: 'Large',
  },
  {
    rank: 54,
    company: 'Henkel AG & Co. KGaA',
    region: 'Europe',
    country: 'Germany',
    sector: 'Consumer Durables',
    industry: 'Package Goods/Cosmetics',
    esg_score: 66.68,
    temperature_score: 1.5,
    emissions_scope_1_2: 686196,
    emissions_scope_3: 3320632,
    market_cap_category: 'Large',
  },
  {
    rank: 55,
    company: 'Novartis AG',
    region: 'Europe',
    country: 'Switzerland',
    sector: 'Health Technology',
    industry: 'Major Pharmaceuticals',
    esg_score: 66.68,
    temperature_score: 1.5,
    emissions_scope_1_2: 1087800,
    emissions_scope_3: 1259200,
    market_cap_category: 'Mega',
  },
  {
    rank: 56,
    company: 'PTT Public company Limited',
    region: 'Asia',
    country: 'Thailand',
    sector: 'Energy Minerals',
    industry: 'Oil & Gas Production',
    esg_score: 66.66,
    temperature_score: '>2.7',
    emissions_scope_1_2: 607258,
    emissions_scope_3: 461783,
    market_cap_category: 'Large',
  },
  {
    rank: 57,
    company: 'PTT Public company Limited',
    region: 'Pacific Rim',
    country: 'Australia',
    sector: 'Energy Minerals',
    industry: 'Oil & Gas Production',
    esg_score: 66.66,
    temperature_score: '>2.7',
    emissions_scope_1_2: 607258,
    emissions_scope_3: 461783,
    market_cap_category: 'Large',
  },
  {
    rank: 58,
    company: 'Glencore PLC',
    region: 'Europe',
    country: 'United Kingdom',
    sector: 'Basic Industries',
    industry: 'Metal Mining',
    esg_score: 66.65,
    temperature_score: '>2.7',
    emissions_scope_1_2: 5570000,
    emissions_scope_3: 10600000,
    market_cap_category: 'Large',
  },
  {
    rank: 59,
    company: 'CRH plc',
    region: 'Europe',
    country: 'Ireland',
    sector: 'Basic Industries',
    industry: 'Building Materials',
    esg_score: 66.63,
    temperature_score: 2,
    emissions_scope_1_2: 254100,
    emissions_scope_3: 246100,
    market_cap_category: 'Large',
  },
  {
    rank: 60,
    company: 'CRH plc',
    region: 'North America',
    country: 'United States',
    sector: 'Basic Industries',
    industry: 'Building Materials',
    esg_score: 66.63,
    temperature_score: 2,
    emissions_scope_1_2: 254100,
    emissions_scope_3: 246100,
    market_cap_category: 'Large',
  },
  {
    rank: 61,
    company: 'VINCI SA',
    region: 'Europe',
    country: 'France',
    sector: 'Basic Industries',
    industry: 'Engineering & Construction',
    esg_score: 66.63,
    temperature_score: 1.5,
    emissions_scope_1_2: 214500,
    emissions_scope_3: 1517600,
    market_cap_category: 'Large',
  },
  {
    rank: 62,
    company: 'Kao Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Household/Personal Care',
    esg_score: 66.61,
    temperature_score: 1.5,
    emissions_scope_1_2: 899000,
    emissions_scope_3: 11184000,
    market_cap_category: 'Large',
  },
  {
    rank: 63,
    company: 'Vicinity Centres',
    region: 'Pacific Rim',
    country: 'Australia',
    sector: 'Finance',
    industry: 'Real Estate Investment Trusts',
    esg_score: 66.6,
    temperature_score: 2,
    emissions_scope_1_2: 274000,
    emissions_scope_3: 1000,
    market_cap_category: 'Large',
  },
  {
    rank: 64,
    company: 'Sumitomo Chemical Co., Ltd.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Basic Industries',
    industry: 'Major Chemicals',
    esg_score: 66.57,
    temperature_score: 1.5,
    emissions_scope_1_2: 1349000,
    emissions_scope_3: 2442000,
    market_cap_category: 'Large',
  },
  {
    rank: 65,
    company: 'Nissan Chemical Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Basic Industries',
    industry: 'Major Chemicals',
    esg_score: 66.57,
    temperature_score: 1.5,
    emissions_scope_1_2: 106900,
    emissions_scope_3: 178200,
    market_cap_category: 'Large',
  },
  {
    rank: 66,
    company: 'Nippon Paint Holdings Co., Ltd.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Durables',
    industry: 'Specialty Chemicals',
    esg_score: 66.56,
    temperature_score: 1.5,
    emissions_scope_1_2: 218400,
    emissions_scope_3: 109200,
    market_cap_category: 'Large',
  },
  {
    rank: 67,
    company: 'Mitsubishi Heavy Industries, Ltd.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Capital Goods',
    industry: 'Industrial Machinery',
    esg_score: 66.56,
    temperature_score: 1.5,
    emissions_scope_1_2: 2665000,
    emissions_scope_3: 2940000,
    market_cap_category: 'Large',
  },
  {
    rank: 68,
    company: 'Kawasaki Heavy Industries, Ltd.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Capital Goods',
    industry: 'Industrial Machinery',
    esg_score: 66.56,
    temperature_score: 1.5,
    emissions_scope_1_2: 1049000,
    emissions_scope_3: 2194000,
    market_cap_category: 'Large',
  },
  {
    rank: 69,
    company: 'Hitachi, Ltd.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Producer Manufacturing',
    industry: 'Industrial Machinery',
    esg_score: 66.55,
    temperature_score: 1.5,
    emissions_scope_1_2: 1889000,
    emissions_scope_3: 4525000,
    market_cap_category: 'Mega',
  },
  {
    rank: 70,
    company: 'DSM',
    region: 'Europe',
    country: 'Netherlands',
    sector: 'Basic Industries',
    industry: 'Major Chemicals',
    esg_score: 66.53,
    temperature_score: 1.5,
    emissions_scope_1_2: 329000,
    emissions_scope_3: 1500000,
    market_cap_category: 'Large',
  },
  {
    rank: 71,
    company: 'Shiseido company, Limited',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Household/Personal Care',
    esg_score: 66.52,
    temperature_score: 1.5,
    emissions_scope_1_2: 74619,
    emissions_scope_3: 2524291,
    market_cap_category: 'Large',
  },
  {
    rank: 72,
    company: 'KDDI Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Communications',
    industry: 'Major Telecommunications',
    esg_score: 66.51,
    temperature_score: 2,
    emissions_scope_1_2: 123158,
    emissions_scope_3: 109031,
    market_cap_category: 'Large',
  },
  {
    rank: 73,
    company: 'Avery Dennison Corporation',
    region: 'North America',
    country: 'United States',
    sector: 'Consumer Durables',
    industry: 'Containers/Packaging',
    esg_score: 66.51,
    temperature_score: 1.5,
    emissions_scope_1_2: 238594,
    emissions_scope_3: 340904,
    market_cap_category: 'Large',
  },
  {
    rank: 74,
    company: 'Suntory Beverage & Food Limited',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Beverages: Non-Alcoholic',
    esg_score: 66.5,
    temperature_score: 1.5,
    emissions_scope_1_2: 482110,
    emissions_scope_3: 4448277,
    market_cap_category: 'Large',
  },
  {
    rank: 75,
    company: 'Brookfield Asset Management Inc',
    region: 'North America',
    country: 'Canada',
    sector: 'Finance',
    industry: 'Investment Managers',
    esg_score: 66.49,
    temperature_score: 2,
    emissions_scope_1_2: 334184,
    emissions_scope_3: 570173,
    market_cap_category: 'Large',
  },
  {
    rank: 76,
    company: 'Eni S.p.A.',
    region: 'Europe',
    country: 'Italy',
    sector: 'Energy Minerals',
    industry: 'Oil & Gas Production',
    esg_score: 66.48,
    temperature_score: '>2.7',
    emissions_scope_1_2: 2099844,
    emissions_scope_3: 3679622,
    market_cap_category: 'Large',
  },
  {
    rank: 77,
    company: 'E.ON SE',
    region: 'Europe',
    country: 'Germany',
    sector: 'Utilities',
    industry: 'Electric Utilities',
    esg_score: 66.47,
    temperature_score: 2,
    emissions_scope_1_2: 119600,
    emissions_scope_3: 2790400,
    market_cap_category: 'Large',
  },
  {
    rank: 78,
    company: 'Woolworths Group Limited',
    region: 'Asia',
    country: 'Australia',
    sector: 'Consumer Services',
    industry: 'Food Retail',
    esg_score: 66.46,
    temperature_score: 1.5,
    emissions_scope_1_2: 15800,
    emissions_scope_3: 182800,
    market_cap_category: 'Large',
  },
  {
    rank: 79,
    company: 'Reckitt Benckiser Group plc',
    region: 'Europe',
    country: 'United Kingdom',
    sector: 'Consumer Durables',
    industry: 'Specialty Chemicals',
    esg_score: 66.44,
    temperature_score: 1.5,
    emissions_scope_1_2: 308000,
    emissions_scope_3: 2653000,
    market_cap_category: 'Large',
  },
  {
    rank: 80,
    company: 'Land Securities Group plc',
    region: 'Europe',
    country: 'United Kingdom',
    sector: 'Consumer Services',
    industry: 'Real Estate Investment Trusts',
    esg_score: 66.43,
    temperature_score: 2,
    emissions_scope_1_2: 109320,
    emissions_scope_3: 78500,
    market_cap_category: 'Large',
  },
  {
    rank: 81,
    company: 'Swiss Re AG',
    region: 'Europe',
    country: 'Switzerland',
    sector: 'Finance',
    industry: 'Property-Casualty Insurers',
    esg_score: 66.42,
    temperature_score: 1.5,
    emissions_scope_1_2: 0,
    emissions_scope_3: 0,
    market_cap_category: 'Large',
  },
  {
    rank: 82,
    company: 'Suntory Holdings Limited',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Beverages: Alcoholic',
    esg_score: 66.42,
    temperature_score: 1.5,
    emissions_scope_1_2: 218825,
    emissions_scope_3: 3870729,
    market_cap_category: 'Large',
  },
  {
    rank: 83,
    company: 'Toyota Tsusho Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Durables',
    industry: 'Automotive Aftermarket',
    esg_score: 66.41,
    temperature_score: 1.5,
    emissions_scope_1_2: 389000,
    emissions_scope_3: 0,
    market_cap_category: 'Large',
  },
  {
    rank: 84,
    company: 'Mitsubishi Chemical Holdings Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Basic Industries',
    industry: 'Major Chemicals',
    esg_score: 66.4,
    temperature_score: 1.5,
    emissions_scope_1_2: 469800,
    emissions_scope_3: 883400,
    market_cap_category: 'Large',
  },
  {
    rank: 85,
    company: 'Chugai Pharmaceutical Co., Ltd.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Health Technology',
    industry: 'Major Pharmaceuticals',
    esg_score: 66.39,
    temperature_score: 1.5,
    emissions_scope_1_2: 150500,
    emissions_scope_3: 583600,
    market_cap_category: 'Large',
  },
  {
    rank: 86,
    company: 'Merck KGaA',
    region: 'Europe',
    country: 'Germany',
    sector: 'Health Technology',
    industry: 'Major Pharmaceuticals',
    esg_score: 66.38,
    temperature_score: 1.5,
    emissions_scope_1_2: 435500,
    emissions_scope_3: 1081900,
    market_cap_category: 'Large',
  },
  {
    rank: 87,
    company: 'Astellas Pharma Inc.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Health Technology',
    industry: 'Major Pharmaceuticals',
    esg_score: 66.38,
    temperature_score: 1.5,
    emissions_scope_1_2: 153400,
    emissions_scope_3: 312100,
    market_cap_category: 'Large',
  },
  {
    rank: 88,
    company: 'SoftBank Group Corp.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Finance',
    industry: 'Major Banks',
    esg_score: 66.37,
    temperature_score: '>2.7',
    emissions_scope_1_2: 195000,
    emissions_scope_3: 142799,
    market_cap_category: 'Mega',
  },
  {
    rank: 89,
    company: 'Ajinomoto Co., Inc.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Packaged Foods',
    esg_score: 66.35,
    temperature_score: 1.5,
    emissions_scope_1_2: 143100,
    emissions_scope_3: 228000,
    market_cap_category: 'Large',
  },
  {
    rank: 90,
    company: 'Singapore Airlines Limited',
    region: 'Asia',
    country: 'Singapore',
    sector: 'Transportation',
    industry: 'Air Freight/Delivery Services',
    esg_score: 66.34,
    temperature_score: 2,
    emissions_scope_1_2: 40000,
    emissions_scope_3: 60000,
    market_cap_category: 'Large',
  },
  {
    rank: 91,
    company: 'Singapore Airlines Limited',
    region: 'Asia',
    country: 'Singapore',
    sector: 'Consumer Services',
    industry: 'Airlines',
    esg_score: 66.34,
    temperature_score: 2,
    emissions_scope_1_2: 40000,
    emissions_scope_3: 60000,
    market_cap_category: 'Large',
  },
  {
    rank: 92,
    company: 'Novo Nordisk A/S',
    region: 'Europe',
    country: 'Denmark',
    sector: 'Health Technology',
    industry: 'Biotechnology: Commercial Physical & Biological Resarch',
    esg_score: 66.33,
    temperature_score: 1.5,
    emissions_scope_1_2: 512600,
    emissions_scope_3: 1208900,
    market_cap_category: 'Large',
  },
  {
    rank: 93,
    company: 'Astellas Pharma Inc.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Health Technology',
    industry: 'Major Pharmaceuticals',
    esg_score: 66.33,
    temperature_score: 1.5,
    emissions_scope_1_2: 153400,
    emissions_scope_3: 312100,
    market_cap_category: 'Large',
  },
  {
    rank: 94,
    company: 'Nissan Motor Co., Ltd.',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Automotive Aftermarket',
    esg_score: 66.32,
    temperature_score: 1.5,
    emissions_scope_1_2: 367100,
    emissions_scope_3: 1332000,
    market_cap_category: 'Large',
  },
  {
    rank: 95,
    company: 'Cathay Pacific Airways Limited',
    region: 'Asia',
    country: 'Hong Kong',
    sector: 'Transportation',
    industry: 'Air Freight/Delivery Services',
    esg_score: 66.31,
    temperature_score: 2,
    emissions_scope_1_2: 116800,
    emissions_scope_3: 454300,
    market_cap_category: 'Large',
  },
  {
    rank: 96,
    company: 'Swire Pacific Limited',
    region: 'Asia',
    country: 'Hong Kong',
    sector: 'Consumer Services',
    industry: 'Building operators',
    esg_score: 66.31,
    temperature_score: 2,
    emissions_scope_1_2: 6900,
    emissions_scope_3: 312100,
    market_cap_category: 'Large',
  },
  {
    rank: 97,
    company: 'Swire Pacific Limited',
    region: 'Pacific Rim',
    country: 'Australia',
    sector: 'Consumer Services',
    industry: 'Building operators',
    esg_score: 66.31,
    temperature_score: 2,
    emissions_scope_1_2: 6900,
    emissions_scope_3: 312100,
    market_cap_category: 'Large',
  },
  {
    rank: 98,
    company: 'Swire Pacific Limited',
    region: 'Asia',
    country: 'Singapore',
    sector: 'Consumer Services',
    industry: 'Building operators',
    esg_score: 66.31,
    temperature_score: 2,
    emissions_scope_1_2: 6900,
    emissions_scope_3: 312100,
    market_cap_category: 'Large',
  },
  {
    rank: 99,
    company: 'Suntory Beverage & Food Limited',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Beverages: Non-Alcoholic',
    esg_score: 66.3,
    temperature_score: 1.5,
    emissions_scope_1_2: 482110,
    emissions_scope_3: 4448277,
    market_cap_category: 'Large',
  },
  {
    rank: 100,
    company: 'Bridgestone Corporation',
    region: 'Asia',
    country: 'Japan',
    sector: 'Consumer Non-Durables',
    industry: 'Automotive Aftermarket',
    esg_score: 66.29,
    temperature_score: 1.5,
    emissions_scope_1_2: 1923000,
    emissions_scope_3: 3631000,
    market_cap_category: 'Large',
  },
] as Company[]
