// Ported verbatim from the old app's Co2SubtitleTooltip.vue / GhgSubtitleTooltip.vue —
// the one piece of prior UX explicitly worth carrying forward into the rewrite.

export const FOSSIL_EMISSIONS_EXPLANATION = 'Fossil emissions measure the quantity of carbon dioxide (CO₂) emitted from the burning of fossil fuels, and directly from industrial processes such as cement and steel production. Fossil CO₂ includes emissions from coal, oil, gas, flaring, cement, steel, and other industrial processes. Fossil emissions do not include land use change, deforestation, soils, or vegetation.'

export const GREENHOUSE_GAS_EXPLANATION = 'A greenhouse gas (GHG) is a gas that causes the atmosphere to warm by absorbing and emitting radiant energy. Greenhouse gases absorb radiation that is radiated by Earth, preventing this heat from escaping to space. Carbon dioxide (CO₂) is the most well-known greenhouse gas, but there are others including methane, nitrous oxide, and in fact, water vapor. Human-made emissions of greenhouse gases from fossil fuels, industry, and agriculture are the leading cause of global climate change. Greenhouse gas emissions measure the total amount of all greenhouse gases that are emitted. These are often quantified in carbon dioxide equivalents (CO₂eq) which take account of the amount of warming that each molecule of different gases creates.'

export const CO2_EQUIVALENTS_EXPLANATION = 'Carbon dioxide is the most important greenhouse gas, but not the only one. To capture all greenhouse gas emissions, researchers express them in "carbon dioxide equivalents" (CO₂eq). This takes all greenhouse gases into account, not just CO₂. To express all greenhouse gases in carbon dioxide equivalents (CO₂eq), each one is weighted by its global warming potential (GWP) value. GWP measures the amount of warming a gas creates compared to CO₂. CO₂ is given a GWP value of one. If a gas had a GWP of 10 then one kilogram of that gas would generate ten times the warming effect as one kilogram of CO₂. Carbon dioxide equivalents are calculated for each gas by multiplying the mass of emissions of a specific greenhouse gas by its GWP factor. This warming can be stated over different timescales. To calculate CO₂eq over 100 years, we\'d multiply each gas by its GWP over a 100-year timescale (GWP100). Total greenhouse gas emissions – measured in CO₂eq – are then calculated by summing each gas\' CO₂eq value.'

export const BENFORDS_LAW_EXPLANATION = 'Benford\'s Law observes that in many naturally occurring collections of numbers, the leading digit is not uniformly distributed: 1 appears as the first digit about 30% of the time, while 9 appears less than 5% of the time. Datasets that deviate substantially from this expected pattern can be worth a closer look — though a deviation on its own is not proof of an error, just a signal.'

export const MAD_EXPLANATION = 'Mean Absolute Deviation (MAD) measures how far a dataset\'s digit distribution is, on average, from the distribution Benford\'s Law predicts. It is the primary conformity signal here because it does not become oversensitive on large datasets the way a chi-square test can — Nigrini\'s bands (Close, Acceptable, Marginal, Nonconformity) classify the result.'

export const CHI_SQUARE_EXPLANATION = 'The chi-square statistic tests whether the observed digit distribution differs from the expected one by more than chance would explain. It is shown as a supporting statistic: with very large datasets, chi-square tends to flag almost any real-world dataset as "non-conforming" even when the deviation is tiny and practically meaningless, so treat it alongside MAD rather than on its own.'
